// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41wPvLSaW4hcTXp8APSbelFE2UEJVKO0',
    appId: '1:640666311692:web:0635ff1c659e964e522229',
    messagingSenderId: '640666311692',
    projectId: 'emailandphoneauth-6ab6d',
    authDomain: 'emailandphoneauth-6ab6d.firebaseapp.com',
    storageBucket: 'emailandphoneauth-6ab6d.appspot.com',
    measurementId: 'G-EQXV7QXLLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJCGAaywbclRT5WUXEDqoe5x-k-BL_c8',
    appId: '1:640666311692:android:0c3e3632d88e8f04522229',
    messagingSenderId: '640666311692',
    projectId: 'emailandphoneauth-6ab6d',
    storageBucket: 'emailandphoneauth-6ab6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfA5vDOPfayjN4W0ZsaFPAoh3YpDyFmGI',
    appId: '1:640666311692:ios:50cce3379a7e122e522229',
    messagingSenderId: '640666311692',
    projectId: 'emailandphoneauth-6ab6d',
    storageBucket: 'emailandphoneauth-6ab6d.appspot.com',
    androidClientId: '640666311692-8mnmujiug6h2bmotn32hpcpa4fv6ck1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfA5vDOPfayjN4W0ZsaFPAoh3YpDyFmGI',
    appId: '1:640666311692:ios:50cce3379a7e122e522229',
    messagingSenderId: '640666311692',
    projectId: 'emailandphoneauth-6ab6d',
    storageBucket: 'emailandphoneauth-6ab6d.appspot.com',
    androidClientId: '640666311692-8mnmujiug6h2bmotn32hpcpa4fv6ck1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQXEuishT2SYL1Yzds0HbughFi6Rdz2OM',
    appId: '1:640666311692:web:0e5f76a5fee70693522229',
    messagingSenderId: '640666311692',
    projectId: 'emailandphoneauth-6ab6d',
    authDomain: 'emailandphoneauth-6ab6d.firebaseapp.com',
    storageBucket: 'emailandphoneauth-6ab6d.appspot.com',
    measurementId: 'G-HJ0W3X3KRE',
  );
}
